### ISSUE TITLE
Does this extension work with Woocommerce variable products?

### ISSUE THREAD

**Issue by alexletizia** [WPCV/wpcv-woo-civi-integration#17]
Do you confirm that this extension is not yet able to work with variable Woocommerce products?

We use Stripe as a payment system and the Woocommerce Name You Price plugin but:

- with SIMPLE PRODUCTS (taxable or non-taxable) the procedure is successful and CiviCRM collects both personal data and contributions

- with PRODUCTS WITH VARIATIONS (taxable or non-taxable) CiviCRM collects only the personal data but not the contributions (and the financial types selected for each single variant are not saved in Woocommerce)

Option: * "Select the WooCommerce Product Types to show the CiviCRM Settings panel on." either leaving it or entering "simple product" that is the only option available.

Thanks.

**Comment by christianwach** [comment]
@alexletizia This plugin does (kind of) work with Variable Products. 

The UI for assigning CiviCRM Settings to the Variations on the Edit Variable Product screen is read-only at the moment - the code to save them hasn't been written yet. 

You can, however, add correctly-configured (e.g. created via the metabox on the _CiviCRM_ -> _WooCommerce_ page) Variations to your Cart/Basket and they should create CiviCRM Contributions correctly.

**Comment by christianwach** [comment]
> "Select the WooCommerce Product Types to show the CiviCRM Settings panel on." either leaving it or entering "simple product" that is the only option available.

@alexletizia Simple Product is the only Product Type available because Variable Products do not use the "CiviCRM Settings" panel and you don't have any other eligible Product Types in WooCommerce.

**Comment by alexletizia** [comment]
@christianwach    Could you please explain better what you mean by "(e.g. created via the metabox on the CiviCRM -> WooCommerce page)"? Our product variations appear to be properly created and managed by Woocommerce but are not generating contributions. Even in "mixed orders" (simple + varied products) the contribution is generated only for simple products and not for the rest of the order.

**Comment by christianwach** [comment]
@alexletizia Do you have a menu item directly below CiviCRM in the left-hand WordPress admin menu? If so, there's a metabox there which will create Variable Products from CiviCRM Events. These Variable Products _will_ create CiviCRM Contributions.

<img width="793" alt="Screenshot 2021-12-01 at 15 43 42" src="https://user-images.githubusercontent.com/726936/144265744-4cea96b1-cb14-41c0-a393-d88dd897b8c4.png">

I'm afraid you will have to wait to create Variable Products via the "Add Product" or "Edit Product" screens - as I said, I haven't written the code that save the CiviCRM settings for each Variation yet.

FYI, the logic for Variable Products is this:

There is a "CiviCRM Settings" panel which allows you to set the CiviCRM Entity Type that applies to *all* Variations. It does not configure anything else, since that is set in the Variations.

![civicrm-panel](https://user-images.githubusercontent.com/726936/144266794-61b8eb66-e3e0-490f-897d-c1a06e097e35.png)

The Variations themselves have CiviCRM settings in their UI (which are read-only until the code is written) that will allow you to specify the settings for each Variation

![civicrm-variations](https://user-images.githubusercontent.com/726936/144266944-8b78e928-b4e0-448f-b2ce-2b134607a8ae.png)

I'll post here when I have news about the code that saves the settings.

**Comment by alexletizia** [comment]
Thanks @christianwach , it is an excellent solution to manage CiviCRM Events through Wocommerce. And we add that it is now clear that the Covid19 pandemic has made it necessary for NPOs to include the "sale" of physical products online as a fundraising activity, for example for Christmas markets. And this we imagine will be a trend for the future. Hopefully you will have time to write the new code.

**Comment by christianwach** [comment]
@alexletizia Try the latest commit and let me know if it works for you. I think it should.

**Comment by christianwach** [comment]
@alexletizia Closing because I think this issue is solved by #18. Feel free to re-open if you find anything wrong.
